#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

use app\core\ConsoleApplication;

require __DIR__ . '/../config/const.php';
require __DIR__ . '/../vendor/autoload.php';

$application = new ConsoleApplication();
$exitCode = $application->run();
exit($exitCode);