<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * 分销佣金接口处理类
 * Author: zal
 * Date: 2020-05-26
 * Time: 10:30
 */

namespace app\plugins\area\forms\api;

use app\core\ApiCode;
use app\models\BaseModel;
use app\models\User;

use app\plugins\area\forms\common\Common;
use app\plugins\area\models\AreaAgent;
use app\plugins\area\models\AreaApply;
use app\plugins\area\models\AreaSetting;


class AreaForm extends BaseModel
{
    public $page;
    public $level;
    public $limit;
    public $status = 0;

    public function rules()
    {
        return [
            [['limit'], 'default', 'value' => 10],
            [['page', 'limit', 'level', 'status'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function getInfo()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getAreaInfo($user);
        if (!$returnData) {
            $apply = AreaApply::find()->where(['user_id' => \Yii::$app->user->identity->id,'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0])->orderBy("id desc")->one();
            $status = 0;
            $reason = "";
            if(!empty($apply)){
                $status = $apply->status;
                $reason = $apply->marks;
            }
            $is_apply = AreaSetting::getValueByKey(AreaSetting::IS_APPLY, \Yii::$app->mall->id);
            $is_apply = $is_apply ?? 0;
            $protocol = AreaSetting::getValueByKey(AreaSetting::PROTOCOL);
            return $this->returnApiResultData(ApiCode::CODE_FAIL, '您不是区域代理，请填写申请信息',
                ['is_area' => 0, 'is_apply' => $is_apply,'protocol'=>$protocol,'status' => $status,"reason" => $reason]);
        }
        $returnData['is_area'] = 1;
        $returnData['user_id'] = \Yii::$app->user->identity->id;
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, $returnData);
    }

    public function getLogList()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $user = User::findOne(\Yii::$app->user->identity->id);
        if (!$user) {
            return $this->returnApiResultData(ApiCode::CODE_FAIL, '请先登录');
        }
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getAreaLogList($user, ['status' => $this->status, 'page' => $this->page]);
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, $returnData);
    }
}