<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-08
 * Time: 15:41
 */

namespace app\plugins\integral_card;


use app\handlers\BaseHandler;
use app\plugins\integral_card\forms\common\Common;
use app\plugins\integral_card\handlers\HandlerRegister;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key' => $this->getName(),
            'name' => '积分',
            'route' => $this->getIndexRoute(),
            'children' => $this->getMenus(),
            'icon' => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ]; // TODO: Change the autogenerated stub
    }

    public function getMenus()
    {
        return [
            [
                'name' => '积分券充值卡',
                'route' => 'plugin/integral_card/admin/card/index',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '赠送来源',
                'route' => 'plugin/integral_card/admin/from-store/list',
                'icon' => 'el-icon-setting',
            ]
        ];
    }

    public function getIndexRoute()
    {
        return 'plugin/integral_card/admin/card/index';
        
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'mall/stock-statistics/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'integral_card';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return '积分';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    public function getLogo()
    {
        // TODO: Implement pluginLogo() method.

        return '';
    }


    public function getPriceTypeName($price_log_id = 0)
    {
        return '未知类型';
    }
}
