#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
require(__DIR__ . '/vendor/autoload.php');
require __DIR__ . '/config/const.php';

$application = new app\core\ConsoleApplication();
$exitCode = $application->run();
exit($exitCode);