<?php
namespace app\plugins\smart_shop;


use app\handlers\BaseHandler;
use app\plugins\stock\handlers\HandlerRegister;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key'         => $this->getName(),
            'name'        => $this->getDisplayName(),
            'route'       => $this->getIndexRoute(),
            'children'    => $this->getMenus(),
            'icon'        => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ];
    }

    public function getMenus()
    {
        return [
            [
                'name' => '全局配置',
                'route' => 'plugin/smart_shop/mall/setting/index',
                'icon' => 'el-icon-setting'
            ],
            [
                'name' => '门店账户明细',
                'route' => 'plugin/smart_shop/mall/store-account/log',
                'icon' => 'el-icon-setting'
            ],
            [
                'name' => '门店支付单',
                'route' => 'plugin/smart_shop/mall/store-pay-order/index',
                'icon' => 'el-icon-setting'
            ],
            [
                'name' => '分账商户',
                'route' => 'plugin/smart_shop/mall/merchant/index',
                'icon' => 'el-icon-setting'
            ],
            /*
            [
                'name' => '小程序管理',
                'route' => 'plugin/smart_shop/mall/mp/wechat',
                'icon' => 'el-icon-setting'
            ],*/
            [
                'name' => '分账订单',
                'route' => 'plugin/smart_shop/mall/order/index',
                'icon' => 'el-icon-setting'
            ],
        ];
    }

    public function getIndexRoute()
    {
        $menus = $this->getMenus();
        return $menus[0]['route'];
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'mall/area-statistics/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'smart_shop';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return '智慧经营';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    public function getLogo()
    {
        // TODO: Implement getLogo() method.
        return '';
    }

    public function getPriceTypeName($price_log_id = 0)
    {
        // TODO: Implement getPriceTypeName() method.
        return '';
    }
}
