<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * 标签设置
 * Author: zal
 * Date: 2020-07-31
 * Time: 16:28
 */

namespace app\forms\mall\setting;

use app\core\ApiCode;
use app\models\BaseModel;
use app\models\Mall;
use app\models\Tag;

class TagForm extends BaseModel
{
    public $data;
    public $cat_id = 1;
    public $id;

    public $limit = 20;
    public $page = 1;

    public function rules()
    {
        return [
            [['limit'], 'default', 'value' => 10],
            [['page', 'limit'], 'integer'],
            [['keywords'],'string']
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * 详情
     * @return array
     */
    public function getDetail()
    {
        $params = [];
        $params["id"] = $this->id;
        $tags = Tag::getData($params);

        $converResult = $this->fieldsConverInt($tags);
        $tags["condition"] = json_encode($converResult);
        $tags["type"] = intval($tags["type"]);

        return [
            'code' => ApiCode::CODE_SUCCESS,
            'msg' => '请求成功',
            'data' => [
                'detail' => $tags
            ],
        ];
    }

    public function save(){
        $returnData = [];
        $data = $this->data;
        if(!isset($data["name"]) || !isset($data["type"]) || !isset($data["data"])){
            $this->returnApiResultData( ApiCode::CODE_FAIL,"缺少参数");
        }

        $conditionData = json_decode($data["data"],true);

        $defaultData = $this->getDefaultConditionData();
        foreach ($defaultData as $key => $val){
            foreach ($conditionData as $k => $vv) {
                if(isset($val[$k]) && $data["type"] == $key){
                    $returnData[$key][$k] = $vv;
                }
            }
        }

        $tagParams = [];
        if(!empty($data["id"])){
            $tagParams["id"] = $data["id"];
        }
        $tagParams["type"] = $data["type"];
        $tagParams["name"] = $data["name"];
        $tagParams["mall_id"] = \Yii::$app->mall->id;
        $tagParams["condition"] = json_encode($returnData);
        $tagParams["cat_id"] = $this->cat_id;
        $result = Tag::operateData($tagParams);
        if($result !== false){
            return $this->returnApiResultData(ApiCode::CODE_SUCCESS, "保存成功");
        }
        return $this->returnApiResultData(ApiCode::CODE_FAIL, "");
    }

    public function getList(){
        $params = [];
        $params["limit"] = $this->limit;
        $params["page"] = $this->page;
        $params["mall_id"] = \Yii::$app->mall->id;
        $list = Tag::getData($params);
        foreach ($list["list"] as &$value){
            $condition = json_decode($value["condition"],true);
            $value["created_at"] = date("Y-m-d H:i:s",$value["created_at"]);
            $value["type_name"] = Tag::$types[$value["type"]];
        }
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, "ok",$list);
    }

    private function getDefaultConditionData(){
        $returnData = [];
        $returnData[1] = [
            "pay_count" => [],
            "pay_money" => []
        ];
        $returnData[2] = [
            "new_user" => [],
            "active_user" => [],
            "silence_user" => [],
            "lose_user" => [],
            "after_purchase_user" => [],
        ];
        $returnData[3] = [
            "direct_drive_num" => [],
            "card_praise_num" => [],
        ];
        $returnData[4] = [
            "buy_kind_goods" => [],
            "collect_kind_goods" => [],
            "search_kind_goods" => [],
            "visit_kind_page" => [],
            "collect_goods" => [],
            "like_num" => [],
            "share_num" => [],
        ];
        return $returnData;
    }

    /**
     * 将string转换int型
     * @param $tags
     * @return mixed
     */
    private function fieldsConverInt($tags){
        $conditionData = json_decode($tags["condition"],true);
        $fields = ["min","max","num"];

        if(!empty($conditionData) && isset($conditionData[$tags["type"]])){
            foreach ($conditionData[$tags["type"]] as $key => &$value){
                foreach ($value as $k=>$v){
                    if(in_array($k,$fields)){
                        $value[$k] = intval($value[$k]);
                    }
                }
            }
        }

        return $conditionData;
    }

}