<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-08
 * Time: 15:41
 */

namespace app\plugins\distribution;


use app\handlers\BaseHandler;
use app\plugins\distribution\forms\common\Common;
use app\plugins\distribution\handlers\HandlerRegister;
use app\plugins\distribution\models\Distribution;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key' => $this->getName(),
            'name' => '分销',
            'route' => $this->getIndexRoute(),
            'children' => $this->getMenus(),
            'icon' => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ]; // TODO: Change the autogenerated stub
    }

    public function getMenus()
    {
        return [
            [
                'name' => '分销商',
                'route' => 'plugin/distribution/mall/distribution/index',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '基础配置',
                'route' => 'plugin/distribution/mall/setting/index',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '申请列表',
                'route' => 'plugin/distribution/mall/distribution/apply',
                'icon' => 'el-icon-setting',

            ],
            [
                'name' => '分销等级',
                'route' => 'plugin/distribution/mall/level/index',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '分销商等级编辑(S|U)',
                        'route' => 'plugin/distribution/mall/level/edit',
                    ],
                ]
            ],
            [
                'name' => '分销提成',
                'route' => 'plugin/distribution/mall/distribution/income-list',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '详情(S|U)',
                        'route' => 'plugin/distribution/mall/distribution/income-detail',
                    ],
                ]
            ],
//            [
//                'name' => '复购提成',
//                'route' => 'plugin/distribution/mall/distribution/rebuy-price-list',
//                'icon' => 'el-icon-setting',
//            ],
//            [
//                'name' => '复购等级',
//                'route' => 'plugin/distribution/mall/level/rebuy-level',
//                'icon' => 'el-icon-setting',
//                'action' => [
//                    [
//                        'name' => '分销商等级编辑(S|U)',
//                        'route' => 'plugin/distribution/mall/level/rebuy-level-edit',
//                    ],
//                ]
//            ],
//            [
//                'name' => '团队奖励',
//                'route' => 'plugin/distribution/mall/level/team',
//                'icon' => 'el-icon-setting',
//            ],
//            [
//                'name' => '团队记录',
//                'route' => 'plugin/distribution/mall/distribution/team-list',
//                'icon' => 'el-icon-setting',
//            ],
//            [
//                'name' => '等级补贴',
//                'route' => 'plugin/distribution/mall/level/subsidy-level',
//                'icon' => 'el-icon-setting',
//                'action' => [
//                    [
//                        'name' => '分销商等级编辑(S|U)',
//                        'route' => 'plugin/distribution/mall/level/subsidy-edit',
//                    ],
//                ]
//            ],
//            [
//                'name' => '补贴记录',
//                'route' => 'plugin/distribution/mall/distribution/subsidy-list',
//                'icon' => 'el-icon-setting',
//            ],

        ];
    }

    public function getIndexRoute()
    {
        return 'plugin/distribution/mall/distribution/index';
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'mall/distribution-statistics/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'distribution';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return '分销';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    /**
     * 获取分销商信息
     * @param \app\models\User $user
     * @return array
     * @throws \Exception
     */
    public function getUserInfo($user)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        /** @var Distribution $distributions */
        $distributions = $common->getDistributionInfo($user);
        return [
            'distribution' => [
                'total_price' => $distributions["total_price"] ?? '0.00',
                'frozen_price' => $distributions["frozen_price"] ?? '0.00',
                'yesterday_price' => $distributions["yesterday_price"] ?? '0.00',
                'level_name' => $distributions["level_name"],
                'sign' => $this->getName(),
                'plugin_name' => $this->getDisplayName(),
                'logo' => $this->getLogo()
            ]
        ];
    }

    /**
     * 获取分销记录列表
     * @param $user
     * @param $params
     * @return array
     * @throws \Exception
     */
    public function getList($user, $params)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getDistributionLogList($user, $params);
        return $returnData;
    }

    /**
     * 获取分销订单
     * @param $order
     * @return array
     * @throws \Exception
     */
    public function getDistributionOrderList($order)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getDistributionOrderList($order);
        return $returnData;
    }

    public function getLogo()
    {
        // TODO: Implement pluginLogo() method.

        return '';
    }

    public function getPriceTypeName($price_log_id = 0)
    {
        // TODO: Implement getPriceTypeName() method.

        return '分销佣金';
    }
}
