<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-12
 * Time: 14:18
 */

namespace app\forms\api;


use app\core\ApiCode;
use app\core\BasePagination;
use app\models\BaseModel;
use app\models\GoodsCollect;


class DemoListForm extends BaseModel
{

    public $page = 1;
    public $limit = 10;


    public function rules()
    {
        return [
            [['page', 'limit'], 'integer'],
            ['page', 'default', 'value' => 1],
            ['limit', 'default', 'value' => 20],
        ]; // TODO: Change the autogenerated stub

    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-05-12
     * @Time: 19:38
     * @Note:获取列表
     * @return array
     */
    public function getList()
    {
        $newList = [];
        /**
         * @var BasePagination $pagination
         *
         */
        $list = GoodsCollect::find()
            ->where(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0, 'user_id' => \Yii::$app->user->id])
            ->page($pagination, $this->limit, $this->page)
            ->all();
        return $this->returnApiResultData(ApiCode::CODE_FAIL, '暂无收藏');
    }


}