<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-29
 * Time: 16:12
 */

namespace app\forms\api\article;


use app\core\ApiCode;
use app\core\BasePagination;
use app\models\Article;
use app\models\BaseModel;

class ArticleForm extends BaseModel
{

    public $id;
    public $page = 1;
    public $limit = 10;
    public $type;

    public function rules()
    {
        return [

            [['page', 'limit', 'id'], 'integer'],
            [['type'],'string'],
            ['page', 'default', 'value' => 1],
            ['limit', 'default', 'value' => 20],
        ]; // TODO: Change the autogenerated stub

    }


    public function getList()
    {

        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        /**
         * @var BasePagination $pagination
         *
         */
        $list = Article::find()
            ->where(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0, 'status' => 1])
            ->orderBy('created_at desc')
            ->page($pagination, $this->limit, $this->page)
            ->all();
        $newList = [];
        /**
         * @var Article $list [];
         */
        foreach ($list as $item) {
            $newItem['title'] = $item->title;
            $newItem['content'] = $item->content;
            $newItem['created_at'] = date('Y-m-d', $item->created_at);
            $newList[] = $newItem;
        }
        if (count($newList)) {
            return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '',
                [
                    'list' => $newList,
                    'page_count' => $pagination->page_count,
                    'total_count' => $pagination->total_count
                ]
            );
        }
        return $this->returnApiResultData(ApiCode::CODE_FAIL, '暂无文章');
    }

    public function getDetail()
    {
        if($this->type&&$this->type=='about_us'){
            $article = Article::findOne(['mall_id' => \Yii::$app->mall->id, 'id' => 1, 'is_delete' => 0,'article_cat_id'=>1]);
        }else{
            $article = Article::findOne(['mall_id' => \Yii::$app->mall->id, 'id' => $this->id, 'is_delete' => 0]);
        }
        if (!$article) {
            return $this->returnApiResultData(ApiCode::CODE_FAIL, '文章不存在！');
        }
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '', ['article' => $article]);
    }


}