<?php

namespace app\plugins\boss\models;

use app\models\BaseActiveRecord;
use app\models\User;
use app\plugins\boss\events\BossInsertEvent;
use app\plugins\boss\handlers\BossInsertHandler;
use Yii;

/**
 * This is the model class for table "{{%plugin_boss}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $user_id
 * @property string|null $remarks 备注
 * @property int $is_delete
 * @property int $created_at 创建时间
 * @property int $deleted_at 删除时间
 * @property int $updated_at 修改时间
 * @property int $upgrade_level_at 分销商等级升级时间
 * @property float $total_price 累计佣金
 * @property float $frozen_price 冻结佣金
 * @property string|null $delete_reason 删除原因
 * @property int $upgrade_status 1条件升级  2 购买指定商品升级   3手动升级
 * @property int $level 经销商等级
 * @property float $extra_price 额外分红金额
 * @property float $level_id 经销商等级id
 * @property User  $user;
 */
class Boss extends BaseActiveRecord
{

    const UPGRADE_STATUS_CONDITION = 1;
    const UPGRADE_STATUS_GOODS = 2;
    const UPGRADE_STATUS_MANUAL = 3;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%plugin_boss}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'user_id'], 'required'],
            [['mall_id', 'user_id', 'is_delete', 'created_at', 'deleted_at', 'updated_at', 'upgrade_level_at', 'upgrade_status', 'level','level_id'], 'integer'],
            [['remarks', 'delete_reason'], 'string'],
            [['total_price', 'frozen_price', 'extra_price'], 'number'],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'user_id' => 'User ID',
            'remarks' => '备注',
            'is_delete' => 'Is Delete',
            'created_at' => '创建时间',
            'deleted_at' => '删除时间',
            'updated_at' => '修改时间',
            'upgrade_level_at' => '分销商等级升级时间',
            'total_price' => '累计佣金',
            'frozen_price' => '冻结佣金',
            'delete_reason' => '删除原因',
            'upgrade_status' => '1条件升级  2 购买指定商品升级   3手动升级',
            'level' => '经销商等级',
            'extra_price' => '额外分红金额',
            'level_id' => '经销商等级ID',
        ];
    }

    public function getUser()
    {
        return $this->hasMany(User::class, ['id' => 'user_id']);
    }

    public function getBossLevel()
    {
        return $this->hasMany(BossLevel::class, ['id' => 'level_id']);
    }


    public function afterSave($insert, $changedAttributes)
    {
        if (!$this->is_delete) {
            //新纪录才去
            if ($insert) {
                Yii::$app->trigger(BossInsertHandler::AGENT_INSERT,
                    new BossInsertEvent(['user_id' => $this->user_id, 'mall_id' => $this->mall_id]));
            } else {
                Yii::warning('不是新增分销商');
            }
        }
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
