<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-08
 * Time: 15:41
 */

namespace app\plugins\stock;


use app\handlers\BaseHandler;
use app\plugins\stock\forms\common\Common;
use app\plugins\stock\handlers\HandlerRegister;
use app\plugins\stock\models\stock;
use app\plugins\stock\models\StockPriceLogType;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key' => $this->getName(),
            'name' => '云库存',
            'route' => $this->getIndexRoute(),
            'children' => $this->getMenus(),
            'icon' => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ]; // TODO: Change the autogenerated stub
    }

    public function getMenus()
    {
        return [
            [
                'name' => '代理商',
                'route' => 'plugin/stock/mall/stock/index',
                'icon' => 'el-icon-setting',

            ],
            [
                'name' => '基础配置',
                'route' => 'plugin/stock/mall/stock/setting',
                'icon' => 'el-icon-setting',

            ],
            [
                'name' => '代理商等级',
                'route' => 'plugin/stock/mall/level/index',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '代理商等级编辑(S|U)',
                        'route' => 'plugin/stock/mall/level/edit',
                    ],
                ]
            ],
            [
                'name' => '升级礼包',
                'route' => 'plugin/stock/mall/level/upgrade-bag',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '礼包编辑(S|U)',
                        'route' => 'plugin/stock/mall/level/upgrade-bag-edit',
                    ],
                ]
            ],

            [
                'name' => '库存商品',
                'route' => 'plugin/stock/mall/goods/index',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '库存商品编辑编辑(S|U)',
                        'route' => 'plugin/stock/mall/goods/edit',
                    ],
                ]
            ],
            [
                'name' => '拿货订单',
                'route' => 'plugin/stock/mall/order/fill-order',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '下级拿货',
                'route' => 'plugin/stock/mall/order/fill-price-log',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '拿货越级奖',
                'route' => 'plugin/stock/mall/stock/over-list',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '礼包记录',
                'route' => 'plugin/stock/mall/stock/upgrade-bag-log',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '出货收益',
                'route' => 'plugin/stock/mall/stock/goods-price-log',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '收益明细',
                'route' => 'plugin/stock/mall/stock/income-list',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '自取订单',
                'route' => 'plugin/stock/mall/stock/agent-order',
                'icon' => 'el-icon-setting',
            ],
        ];
    }

    public function getIndexRoute()
    {
        return 'plugin/stock/mall/stock/index';
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'mall/stock-statistics/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'stock';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return '云库存';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    /**
     * 获取代理商信息
     * @param \app\models\User $user
     * @return array
     * @throws \Exception
     */
    public function getUserInfo($user)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        /** @var stock $agents */
        $agents = $common->getAgentInfo($user);
        return [
            'stock' => [
                'total_price' => $agents["total_price"] ?? '0.00',
                'frozen_price' => $agents["frozen_price"] ?? '0.00',
                'yesterday_price' => $agents["yesterday_price"] ?? '0.00',
                'level_name' => $agents["level_name"],
                'sign' => $this->getName(),
                'plugin_name' => $this->getDisplayName(),
                'logo' => $this->getLogo()
            ]
        ];
    }

    /**
     * 获取经销记录列表
     * @param $user
     * @param $params
     * @return array
     * @throws \Exception
     */
    public function getList($user, $params)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getAgentLogList($user, $params);
        return $returnData;
    }

    /**
     * 获取经销订单
     * @param $order
     * @return array
     * @throws \Exception
     */
    public function getAgentOrderList($order)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getAgentOrderList($order);
        return $returnData;
    }

    public function getLogo()
    {
        // TODO: Implement pluginLogo() method.

        return '';
    }


    public function getPriceTypeName($price_log_id = 0)
    {
        // TODO: Implement getPriceTypeName() method.
        $price_type = StockPriceLogType::findOne(['price_log_id' => $price_log_id]);
        if ($price_type) {
            return StockPriceLogType::getTypeName($price_type->type);
        }
        return '未知类型';
    }
}
