<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-04-10
 * Time: 20:53
 */

namespace app\forms\mall\cat;

use app\models\BaseModel;
use app\models\Cat;
use yii\base\Model;
use yii\data\Pagination;

class CatListForm extends BaseModel
{
    public $mall_id;
    public $limit;
    public $page;


    public function rules()
    {
        return [
            [['page', 'limit'], 'integer'],
            [['page',], 'default', 'value' => 1],
            [['limit',], 'default', 'value' => 20],
        ]; // TODO: Change the autogenerated stub
    }




    public function search()
    {
        $query = Cat::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0]);
        $count = $query->count();
        $pagination = new Pagination(['totalCount' => $count, 'page' => $this->page - 1, 'pageSize' => $this->limit,]);
        /* @var Goods[] $list */
        $list = $query->orderBy('updated_at DESC')->limit($pagination->limit)->offset($pagination->offset)->all();
        return [
            'code' => 0,
            'msg' => 'success',
            'data' => [
                'row_count' => $count,
                'page_count' => $pagination->pageCount,
                'list' => $list,
            ],
        ];

    }


}