<?php

namespace app\plugins\mch\controllers\api\mana;

use app\controllers\api\ApiController;
use app\plugins\mch\controllers\api\mana\filter\LoginFilter;
use app\plugins\mch\forms\api\MchAdminAuthMobileForm;

class MchAdminController extends ApiController {

    public static $adminUser = null;

    public function behaviors(){
        return array_merge(parent::behaviors(), [
            'login' => [
                'class' => LoginFilter::class,
                'ignore' => [
                    'plugin/mch/api/mana/mch-admin/auth-mobile',
                ]
            ]
        ]);
    }

    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 通过手机号登录
     * @return yii\web\Response
     * @throws \Exception
     */
    public function actionAuthMobile(){
        $form = new MchAdminAuthMobileForm();
        $form->attributes = $this->requestData;
        return $this->asJson($form->login());
    }

}