<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-23
 * Time: 15:33
 */

namespace app\forms\mall\shop;


use app\core\ApiCode;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\models\HomePage;

class DiyForm extends BaseModel
{


    public $page_data;

    public function rules()
    {
        return [
            [['page_data'], 'required'],
            [['page_data'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }


    public function savePageData()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $model = HomePage::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id]);

        if (!$model) {
            $model = new HomePage();
            $model->mall_id = \Yii::$app->mall->id;
        }
        $model->page_data = $this->page_data;
        if (!$model->save()) {
            return $this->responseErrorMsg($model);
        }
        return ['code' => ApiCode::CODE_SUCCESS, 'msg' => '保存成功'];
    }


    public function getPageData()
    {
        $model = HomePage::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id]);
        if ($model) {
            $model->page_data = SerializeHelper::decode($model->page_data);
            return $model->page_data;
        }
        return null;
    }


    /**
     * 所有组件
     * @return array
     */
    public function allComponents()
    {
        $diyIconUrl = "statics/img/mall/diy/components";
        return [
            [
                'groupName' => '基础组件',
                'list' => [
                    [
                        'id' => 'search',
                        'name' => '搜索',
                        'icon' => $diyIconUrl . '/search.png',
                    ],
                    [
                        'id' => 'nav',
                        'name' => '导航图标',
                        'icon' => $diyIconUrl . '/nav.png',
                    ],
                    [
                        'id' => 'banner',
                        'name' => '轮播广告',
                        'icon' => $diyIconUrl . '/banner.png',
                    ],
                    [
                        'id' => 'notice',
                        'name' => '公告',
                        'icon' => $diyIconUrl . '/notice.png'
                    ],
                    [
                        'id' => 'topic',
                        'name' => '专题',
                        'icon' => $diyIconUrl . '/topic.png',
                        'key' => 'topic'
                    ],
//                    [
//                        'id' => 'link',
//                        'name' => '关联链接',
//                        'icon' => $diyIconUrl . '/link.png',
//                    ],
                    [
                        'id' => 'rubik',
                        'name' => '图片广告',
                        'icon' => $diyIconUrl . '/rubik.png',
                    ],
                    [
                        'id' => 'video',
                        'name' => '视频',
                        'icon' => $diyIconUrl . '/video.png',
                        'key' => 'video'
                    ],
                    [
                        'id' => 'goods',
                        'name' => '商品',
                        'icon' => $diyIconUrl . '/goods.png',
                    ],
//                    [
//                        'id' => 'empty',
//                        'name' => '空白块',
//                        'icon' => $diyIconUrl . '/empty.png'
//                    ],
                    [
                        'id' => 'map',
                        'name' => '地图',
                        'icon' => $diyIconUrl . '/map.png',
                    ],

                    [
                        'id' => 'image-text',
                        'name' => '图文详情',
                        'icon' => $diyIconUrl . '/image-text.png',
                    ],
                    [
                        'id' => 'label-bar',
                        'name' => '标签栏',
                        'icon' => $diyIconUrl . '/nav.png',
                        'single' => true,
                        'is_last'=>true
                    ],
                    [
                        'id' => 'dynamic-goods',
                        'name' => '动态商品',
                        'icon' => $diyIconUrl . '/goods.png',
                    ],
                ]
            ],
            [
                'groupName' => '其他组件',
                'list' => [
                    [
                        'id' => 'modal',
                        'name' => '弹窗广告',
                        'icon' => $diyIconUrl . '/modal.png',
                        'single' => true,
                    ],
//                    [
//                        'id' => 'quick-nav',
//                        'name' => '快捷导航',
//                        'icon' => $diyIconUrl . '/float.png',
//                        'single' => true,
//                    ],
                ]
            ]
        ];

    }


}