<?php
namespace app\mch\controllers;

use app\core\ApiCode;
use yii\web\Controller;

/**
 * Class BaseController
 * @package app\controllers
 * @Notes 基础控制器负责获取一些常用的变量，例如mall_id
 */
class BaseController extends Controller{

    public $enableCsrfValidation = false;
    public $mall_id;//商城id
    public $pageSize = 10;

    public function init(){
        header("Origin:*");
        header("Access-Control-Allow-Origin:*");
        header("Access-Control-Request-Headers:*");
        header("Access-Control-Allow-Credentials:true");
        header("Access-Control-Request-Method:*");
        header("Access-Control-Allow-Headers: Content-Type, X-Requested-With, Cache-Control,Authorization");

        $mchModel = \Yii::$app->mchAdmin->identity->mchModel;
        if (!$mchModel) {
            return ['code' => ApiCode::CODE_MALL_NOT_EXIST, 'msg' => '商户不存在'];
        }

        $this->mall_id = $mchModel->mall_id;

        \Yii::$app->setMallId($this->mall_id);

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 请求成功统消息格式化处理
     * @param array $url
     * @param string $msg
     * @param array $data
     * @return void
     */
    public function success($msg='success',$data=[],$url=[]){
        return $this->asJson(array(
            'code' => ApiCode::CODE_SUCCESS,
            'msg' => $msg,
            'data' => $data
        ));
    }

    /**
     * 请求失败消息格式化处理
     * @param array $url
     * @param string $msg
     * @param array $data
     * @return void
     */
    public function error($msg='failed',$data=[],$url=[]){
        return $this->asJson(array(
            'code'  => ApiCode::CODE_FAIL,
            'msg'   => $msg,
            'data'  => $data
        ));
    }
}