<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-28
 * Time: 9:35
 */

namespace app\plugins\mpwx\controllers\api;

use app\plugins\ApiController;
use app\plugins\mpwx\models\MpwxConfig;

class Controller extends ApiController
{

    public $app = null;
    public $payment = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $config = MpwxConfig::findOne(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        if ($config) {
            \Yii::$app->params['wechatMiniProgramConfig'] = [
                'app_id' => $config->app_id,
                'secret' => $config->secret,
                'response_type' => 'array',
            ];
            \Yii::$app->params['wechatPaymentConfig'] = [
                'app_id' => $config->app_id,
                'mch_id' => $config->mch_id,
                'key' => $config->pay_secret,
                'cert_path' => $config->cert_pem_path, // XXX: 绝对路径！！！！
                'key_path' => $config->key_pem_path,      // XXX: 绝对路径！！！！
                'notify_url' => '',     // 你也可以在下单时单独设置来想覆盖它
            ];
            $this->app = \Yii::$app->wechat->miniProgram;
            $this->payment = \Yii::$app->wechat->payment;
        }
    }


}