<?php
namespace app\plugins\income_log;


use app\handlers\BaseHandler;
use app\helpers\PluginHelper;
use app\plugins\stock\handlers\HandlerRegister;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key'         => $this->getName(),
            'name'        => $this->getDisplayName(),
            'route'       => $this->getIndexRoute(),
            'children'    => $this->getMenus(),
            'icon'        => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ];
    }

    public function getMenus()
    {
        return [
            [
                'name' => '基本设置',
                'route' => 'plugin/income_log/mall/setting/index',
                'icon' => 'el-icon-setting'
            ],

        ];
    }

    public function getIndexRoute()
    {
        $menus = $this->getMenus();
        return $menus[0]['route'];
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'plugin/income_log/mall/setting/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'income_log';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return '收益管理';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    public function getLogo()
    {
        // TODO: Implement getLogo() method.
        return '';
    }

    public function getPriceTypeName($price_log_id = 0)
    {
        // TODO: Implement getPriceTypeName() method.
        return '';
    }

    /* 插件可共用的跳转链接
     * @return array
    */
    public function getPickLink()
    {
        $iconBaseUrl = PluginHelper::getPluginBaseAssetsUrl($this->getName()) . '/img/pick-link';
        $iconUrlPrefix = \Yii::$app->request->hostInfo . \Yii::$app->request->baseUrl .
            '/statics/img/mall/pick-link/';
        return [
            [
                'type' => 'income_index',
                'name' => '我的收益',
                'open_type' => '',
                'icon' => $iconUrlPrefix . 'icon-article-detail.png',
                'value' => '/plugins/income_log/index'
            ],
        ];
    }
}
