<?php

namespace app\plugins\mch\controllers\api;

use app\controllers\api\filters\LoginFilter;
use app\plugins\mch\controllers\api\filter\MchLoginFilter;

class ApiController extends \app\controllers\api\ApiController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'login' => [
                'class' => LoginFilter::class,
            ],
            'mchLogin' => [
                'class' => MchLoginFilter::class,
            ]
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
