<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-27
 * Time: 11:19
 */

namespace app\controllers\api;


use app\controllers\api\filters\LoginFilter;
use app\forms\api\topic\TopicForm;

class TopicController extends ApiController
{

    public function behaviors()
    {
        return array_merge(parent::behaviors(), ['login' => [
            'class' => LoginFilter::class,
            'only' => ['favorite']
        ]]); // TODO: Change the autogenerated stub
    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-05-27
     * @Time: 11:25
     * @Note:专题分类
     * @return array|mixed
     */
    public function actionType()
    {
        $form = new TopicForm();
        $form->attributes = $this->requestData;
        return $form->getTypeList();
    }

    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-06-01
     * @Time: 16:04
     * @Note:专题列表
     * @return array
     */
    public function actionList()
    {
        $form = new TopicForm();
        $form->attributes = $this->requestData;
        return $form->getList();
    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-05-27
     * @Time: 11:28
     * @Note:专题详情
     * @return array
     */
    public function actionDetail()
    {
        $form = new TopicForm();
        $form->attributes = $this->requestData;
        return $form->getDetail();
    }

    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-05-27
     * @Time: 11:28
     * @Note:喜欢的专题
     * @return array
     */
    public function actionFavorite()
    {
        $form = new TopicForm();
        $form->attributes = $this->requestData;
        return $form->favorite();
    }

}