<?php

namespace app\plugins\distribution\models;

use app\models\BaseActiveRecord;
use app\models\User;
use app\models\UserChildren;
use app\models\UserGrowth;
use app\models\UserParent;
use app\plugins\distribution\events\DistributionInsertEvent;
use app\plugins\distribution\handlers\DistributionInsertHandler;
use Yii;

/**
 * This is the model class for table "{{%plugin_distribution}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $user_id
 * @property string|null $remarks 备注
 * @property int $is_delete
 * @property int $created_at 创建时间
 * @property int $deleted_at 删除时间
 * @property int $updated_at 修改时间
 * @property int $total_childs 所有下级数量
 * @property int $total_order 分销订单数量
 * @property int $level 分销商等级
 * @property int $upgrade_level_at 分销商等级升级时间
 * @property float $total_price 佣金
 * @property float $frozen_price 冻结佣金
 * @property User $user
 * @property string $delete_reason 删除原因
 * @property int $upgrade_status
 *
 * @property DistributionLevel $distributionLevel
 */
class Distribution extends BaseActiveRecord
{

    const UPGRADE_STATUS_CONDITION = 1;
    const UPGRADE_STATUS_GOODS = 2;
    const UPGRADE_STATUS_MANUAL = 3;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%plugin_distribution}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'user_id'], 'required'],
            [['mall_id', 'user_id', 'is_delete', 'created_at', 'deleted_at', 'updated_at', 'total_childs', 'total_order', 'level', 'upgrade_level_at', 'upgrade_status'], 'integer'],
            [['remarks', 'delete_reason'], 'string'],
            [['total_price','frozen_price'], 'number'],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'user_id' => 'User ID',
            'remarks' => '备注',
            'is_delete' => 'Is Delete',
            'created_at' => '创建时间',
            'deleted_at' => '删除时间',
            'updated_at' => '修改时间',
            'total_childs' => '所有下级数量',
            'total_order' => '分销订单数量',
            'level' => '分销商等级',
            'upgrade_level_at' => '分销商等级升级时间',
            'total_price' => '总佣金',
            'frozen_price' => '冻结佣金',
            'delete_reason' => '删除原因',
            'upgrade_status' => '升级方式，1条件升级 2 购买指定商品升级 3手动升级'
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function getDistributionLevel()
    {
        return $this->hasOne(DistributionLevel::class, ['level' => 'level'])->where(['is_delete' => self::NO]);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!$this->is_delete) {
            //新纪录才去
            if ($insert) {
                Yii::warning('新分销商');
                Yii::$app->trigger(DistributionInsertHandler::DISTRIBUTION_INSERT,
                    new DistributionInsertEvent(['user_id' => $this->user_id, 'mall_id' => $this->mall_id]));
            } else {
                Yii::warning('不是新增分销商');

            }
        }


        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
