<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-08
 * Time: 15:41
 */

namespace app\plugins\area;


use app\handlers\BaseHandler;
use app\plugins\area\forms\common\Common;
use app\plugins\area\handlers\HandlerRegister;
use app\plugins\area\models\area;
use app\plugins\area\models\AreaPriceLogType;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key' => $this->getName(),
            'name' => '区域',
            'route' => $this->getIndexRoute(),
            'children' => $this->getMenus(),
            'icon' => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ]; // TODO: Change the autogenerated stub
    }

    public function getMenus()
    {
        return [
            [
                'name' => '区域代理',
                'route' => 'plugin/area/mall/area/index',
                'icon' => 'el-icon-setting',

            ],
            [
                'name' => '申请列表',
                'route' => 'plugin/area/mall/area/apply',
                'icon' => 'el-icon-setting',

            ],
            [
                'name' => '基础配置',
                'route' => 'plugin/area/mall/area/setting',
                'icon' => 'el-icon-setting',

            ],
            [
                'name' => '提成明细',
                'route' => 'plugin/area/mall/area/income-list',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '详情(S|U)',
                        'route' => 'plugin/area/mall/area/income-detail',
                    ],
                ]
            ],
        ];
    }

    public function getIndexRoute()
    {
        return 'plugin/area/mall/area/index';
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'mall/area-statistics/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'area';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return '区域';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    /**
     * 获取经销商信息
     * @param \app\models\User $user
     * @return array
     * @throws \Exception
     */
    public function getUserInfo($user)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        /** @var area $areas */
        $areas = $common->getAreaInfo($user);
        return [
            'area' => [
                'total_price' => $areas["total_price"] ?? '0.00',
                'frozen_price' => $areas["frozen_price"] ?? '0.00',
                'yesterday_price' => $areas["yesterday_price"] ?? '0.00',
                'level_name' => $areas["level_name"],
                'sign' => $this->getName(),
                'plugin_name' => $this->getDisplayName(),
                'logo' => $this->getLogo()
            ]
        ];
    }

    /**
     * 获取经销记录列表
     * @param $user
     * @param $params
     * @return array
     * @throws \Exception
     */
    public function getList($user, $params)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getAreaLogList($user, $params);
        return $returnData;
    }

    /**
     * 获取经销订单
     * @param $order
     * @return array
     * @throws \Exception
     */
    public function getAreaOrderList($order)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getAreaOrderList($order);
        return $returnData;
    }

    public function getLogo()
    {
        // TODO: Implement pluginLogo() method.

        return '';
    }


    public function getPriceTypeName($price_log_id = 0)
    {

        return '区域分红';
        // TODO: Implement getPriceTypeName() method.
        $price_type = AreaPriceLogType::findOne(['price_log_id' => $price_log_id]);
        if ($price_type) {
            return AreaPriceLogType::getTypeName($price_type->type);
        }
        return '未知类型';
    }
}
