<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-04-29
 * Time: 19:10
 */

namespace app\forms\mall\goods;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\Label;

class LabelForm extends BaseModel
{


    public $id;

    public function rules()
    {
        return [
            [['id'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }


    public function search()
    {

        if(!$this->validate()){

            return $this->responseErrorInfo();
        }

        $label = Label::findOne(['id' => $this->id, 'is_delete' => 0]);
        if (!$label) {
            return ['code' => ApiCode::CODE_FAIL, 'msg' => '该标签不存在！'];
        }
        return ['code' => ApiCode::CODE_SUCCESS, 'msg' => '数据请求成功！', 'data' => $label];
    }
}