<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-10
 * Time: 21:37
 */

namespace app\plugins\boss\forms\mall;


use app\core\ApiCode;
use app\plugins\boss\models\Boss;
use app\models\BaseModel;


class BossRemarksForm extends BaseModel
{

    public $id;
    public $remarks;


    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
            [['remarks'], 'string']


        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @Author: 广东七件事 ganxiaohao
     * Date: 2020-05-10
     * Time: 21:39
     * @Note:保存备注
     */
    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $boss = Boss::findOne(['id' => $this->id, 'is_delete' => 0]);
        if (!$boss) {
            return ['code' => ApiCode::CODE_FAIL, 'msg' => '该分销商不存在'];
        }

        $boss->remarks = $this->remarks;
        if (!$boss->save()) {
            return $this->responseErrorMsg($boss);
        }
        return  ['code'=>ApiCode::CODE_SUCCESS,'msg'=>'保存成功'];
    }



}