<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-04-22
 * Time: 20:24
 */

namespace app\forms\mall\wechat;


use app\core\ApiCode;
use yii\web\UploadedFile;

class MaterialUploadForm
{
    /** @var UploadedFile $file */
    public $file;
    public $savePath;
    public $saveThumbFolder;//缩略图
    public $saveName;
    public $url;
    public $thumb_url;
    public $baseWebUrl;
    public $baseWebPath;
    public $saveFile;

    protected $imageExt = ['jpg', 'bmp', 'png', 'gif', 'jpeg', 'webp',];
    protected $videoExt = ['mp4',];
    protected $voiceExt = ['mp3', 'wma', 'wav', 'amr'];//mp3/wma/wav/amr
    public $file_path;

    public function rules()
    {
        return [
            [['file'], 'file'],
            [['file'], 'validateFileExt'],

        ]; // TODO: Change the autogenerated stub
    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-04-22
     * @Time: 20:27
     * @Note:验证文件
     * @param $a
     * @return bool
     */
    public function validateFileExt($a)
    {
        $allSupportExt = array_merge($this->imageExt, $this->videoExt, $this->voiceExt);
        if (!in_array($this->file->getExtension(), $allSupportExt)) {
            $this->addError($a, '不支持' . $this->file->getExtension() . '的文件！');
            return false;
        }
        return true;
    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-04-02
     * @Time: 19:49
     * @Note:文件数据保存
     */
    public function save()
    {
        if (!$this->validateFileExt("file")) {
            return ['code' => ApiCode::CODE_FAIL, 'msg' => '不支持' . $this->file->getExtension() . '的文件！'];
        }
        $this->baseWebPath = \Yii::$app->basePath . '/web';
        $this->baseWebUrl=\Yii::$app->request->hostInfo.'/web';
        $dateFolder = date('Ymd');
        $this->savePath = '/uploads/material/original/' . $dateFolder . '/';
        $this->saveName = md5_file($this->file->tempName) . '.' . $this->file->getExtension();
        $this->file_path = $this->savePath . $this->saveName;
        $this->saveFile = $this->baseWebPath . $this->savePath . $this->saveName;
        $res = $this->saveToLocal();

        return ['code' => ApiCode::CODE_SUCCESS, 'msg' => 'success', 'data' => $res];
    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-04-22
     * @Time: 20:29
     * @Note:素材保存到本地
     * @return array
     * @throws \Exception
     */
    public function saveToLocal()
    {
        $this->url = $this->savePath . $this->saveName;
        if (!is_dir($this->baseWebPath . $this->savePath)) {
            if (!make_dir($this->baseWebPath . $this->savePath)) {
                throw new \Exception('上传失败，创建文件夹失败`'
                    . $this->baseWebPath
                    . $this->savePath
                    . '`，请检查目录写入权限。');
            }
        }
        if (!$this->file->saveAs($this->saveFile)) {
            if (!copy($this->file->tempName, $this->saveFile)) {
                throw new \Exception('文件保存失败，请检查目录写入权限。');
            }
        }
        $this->thumb_url = $this->baseWebUrl . '/' . $this->url;
        return ['url' => $this->url, 'extension' => $this->file->getExtension(), 'size' => $this->file->size, 'thumb_url' => $this->thumb_url, 'name' => $this->file->name];
    }


}