<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: zal
 * Date: 2020-09-23
 * Time: 18:59
 */

namespace app\plugins\stock\forms\mall;


use app\core\ApiCode;
use app\models\BaseModel;
use app\plugins\stock\models\StockGoods;

class StockGoodsDeleteForm extends BaseModel
{

    public $id;

    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {

        if (!$this->validate()) {

            return $this->responseErrorInfo();
        }
        $stockGoods = StockGoods::findOne(['id' => $this->id, 'is_delete' => 0]);

        if (empty($stockGoods)) {
            return ['code' => ApiCode::CODE_FAIL, 'msg' => '所选择的库存商品不存在或已删除，请刷新后重试'];
        }

        $stockGoods->is_delete = StockGoods::IS_DELETE_YES;
        if($stockGoods->save() === false){
            return ['code' => ApiCode::CODE_SUCCESS, 'msg' => '删除失败！'];
        }

        return ['code' => ApiCode::CODE_SUCCESS, 'msg' => '删除成功！'];

    }


}