<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * 分销申请接口处理类
 * Author: zal
 * Date: 2020-05-26
 * Time: 14:30
 */

namespace app\plugins\distribution\forms\api;

use app\core\ApiCode;
use app\models\BaseModel;
use app\models\User;
use app\plugins\distribution\models\Distribution;
use app\plugins\distribution\models\DistributionApply;
use app\plugins\distribution\models\DistributionSetting;


class DistributionApplyForm extends BaseModel
{

    public $realname;
    public $mobile;
    public $marks;

    public function rules()
    {
        return [
            [['realname', 'mobile'], 'required'],
            [['realname', 'mobile'], 'string', 'max' => 45],
            [['marks'], 'string', 'max' => 255],
        ]; // TODO: Change the autogenerated stub
    }

    public function apply()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        /** @var DistributionApply $apply */
        $apply = DistributionApply::find()->where(['user_id' => \Yii::$app->user->identity->id,'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0])->orderBy("id desc")->one();
        if (!empty($apply)) {
            if($apply->status == DistributionApply::STATUS_WAIT_REVIEW){
                return $this->returnApiResultData(ApiCode::CODE_FAIL, '您已经提交了申请,请耐心等待处理');
            }else if($apply->status == DistributionApply::STATUS_PASS){
                return $this->returnApiResultData(ApiCode::CODE_FAIL, '您已经通过审核成为分销商，无需再申请');
            }
        }
        $distributions = Distribution::find()->where(["user_id" => \Yii::$app->user->identity->id,'mall_id' => \Yii::$app->mall->id,"is_delete" => Distribution::IS_DELETE_NO])->one();
        if(!empty($distributions)){
            return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '您已经是分销商');
        }
        $apply = new DistributionApply();
        $apply->attributes = $this->attributes;
        $apply->mall_id = \Yii::$app->mall->id;
        $apply->user_id = \Yii::$app->user->identity->id;
        if (!$apply->save()) {
            return $this->returnApiResultData(ApiCode::CODE_FAIL, '保存失败', ['error' => $apply->getErrors()]);
        }
        $is_apply = DistributionSetting::getValueByKey(DistributionSetting::IS_APPLY, \Yii::$app->mall->id);
        $is_check = DistributionSetting::getValueByKey(DistributionSetting::IS_CHECK, \Yii::$app->mall->id);
        $user = User::findOne($apply->user_id);
        //需要申请，但是不需要审核
        if ($is_apply == 1 && $is_check == 0) {
            $distribution = new Distribution();
            $distribution->mall_id = $apply->mall_id;
            $distribution->user_id = $apply->user_id;
            $distribution->created_at = time();
            $distribution->level = 0;
            $distribution->is_delete = 0;
            if ($distribution->save()) {
                if (!$user->is_inviter) {
                    $user->is_inviter = User::IS_INVITER_YES;
                    $user->inviter_at = time();
                    $user->is_distributor = User::YES;
                    $user->save();
                }
                $apply->status = 1;
                $apply->marks = '审核通过';
                $apply->save();
                return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '恭喜您成为分销商，请退出后再次进入');
            }
        }
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '提交成功,请耐心等待处理');
    }
}