<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * 分销佣金接口处理类
 * Author: zal
 * Date: 2020-05-26
 * Time: 10:30
 */

namespace app\plugins\distribution\forms\api;

use app\core\ApiCode;
use app\models\BaseModel;
use app\models\User;
use app\plugins\distribution\forms\common\Common;
use app\plugins\distribution\models\Distribution;
use app\plugins\distribution\models\DistributionApply;
use app\plugins\distribution\models\DistributionSetting;


class DistributionForm extends BaseModel
{
    public $page;
    public $level;
    public $limit;

    public function rules()
    {
        return [
            [['limit'], 'default', 'value' => 10],
            [['page', 'limit', 'level'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function getInfo()
    {
        /*$user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);

        $returnData = $common->getDistributionInfo($user);
        if (!$returnData["is_distribution"]) {
            $is_apply = DistributionSetting::getValueByKey(DistributionSetting::IS_APPLY, \Yii::$app->mall->id);
            if($is_apply == DistributionApply::YES){
                $apply = DistributionApply::find()->where(['user_id' => \Yii::$app->user->identity->id,'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0])->orderBy("id desc")->one();
                $status = 0;
                $reason = "";
                if(!empty($apply)){
                    $status = $apply->status;
                    $reason = $apply->marks;
                }
                $protocol = DistributionSetting::getValueByKey(DistributionSetting::PROTOCOL);
                return $this->returnApiResultData(ApiCode::CODE_FAIL, '您不是分销商，请填写申请信息',
                    ['is_distribution' => 0, 'is_apply' => $is_apply,'protocol' => $protocol,'status' => $status,'reason' => $reason]);
            }
        }*/

        $returnData = [
            'avatar_url'        => '',
            'parent_level_name' => '',
            'parent_name'       => ''
        ];

        $user = User::findOne(\Yii::$app->user->identity->id);
        if($user){
            $parent = User::findOne($user->parent_id);
            if($parent){
                $parentLevel                     = $parent->getUserLevel();
                $returnData['avatar_url']        = $parent->avatar_url;
                $returnData['parent_level_name'] = $parentLevel['name'];
                $returnData['parent_name']       = $parent->nickname;
            }
        }

        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, ['info' => $returnData]);
    }


    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-08-04
     * @Time: 16:31
     * @Note:获取复购数据
     */
    public function getRebuyInfo()
    {
        $user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);
        /** @var Distribution $distributions */
        $returnData = $common->getDistributionInfo($user);


    }

    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-07-22
     * @Time: 11:27
     * @Note: 分销记录
     * @return array
     * @throws \Exception
     */
    public function getLogList()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getDistributionLogList($user, ['level' => $this->level, 'page' => $this->page]);
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, $returnData);
    }

    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-07-22
     * @Time: 11:27
     * @Note:获取复购奖励
     * @return array
     * @throws \Exception
     */
    public function getRebuyPriceList()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getRebuyPriceList($user, ['page' => $this->page]);
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, $returnData);
    }

    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-08-04
     * @Time: 16:47
     * @Note:团队奖励
     * @return array
     * @throws \Exception
     */
    public function getTeamPriceList()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getTeamPriceList($user, ['page' => $this->page]);
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, $returnData);
    }



    /**
     * @Author: 广东七件事 ganxiaohao
     * @Date: 2020-07-22
     * @Time: 11:27
     * @Note:获取补贴
     * @return array
     * @throws \Exception
     */
    public function getSubsidyPriceList()
    {
        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $user = User::findOne(\Yii::$app->user->identity->id);
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getSubsidyPriceList($user, ['page' => $this->page]);
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, null, $returnData);
    }

}