<?php

namespace app\plugins\smart_shop\components;

use yii\base\Component;

class AlipaySdkApi extends Component{

    public $appId;
    public $rsaPrivateKeyPath;
    public $alipayrsaPublicKeyPath;

    private $aop = null;

    public function init(){
        parent::init(); // TODO: Change the autogenerated stub

    }

    public function getAop(){
        if($this->aop == null){
            require_once __DIR__ . "/alipay_sdk/AopClient.php";
            $aop = new \AopClient ();

            $aop->gatewayUrl         = 'https://openapi.alipay.com/gateway.do';
            $aop->appId              = $this->appId;

            $aop->rsaPrivateKey      = file_get_contents($this->rsaPrivateKeyPath);
            $aop->alipayrsaPublicKey = file_get_contents($this->alipayrsaPublicKeyPath);
            $aop->apiVersion         = '1.0';
            $aop->signType           = 'RSA2';
            $aop->postCharset        = 'UTF-8';
            $aop->format             = 'json';
            $this->aop = $aop;
        }
        return $this->aop;
    }

    /**
     * 统一收单线下交易查询
     * @param $params
     * @param $appAuthToken
     */
    public function tradeQuery($params, $appAuthToken = null){
        require_once __DIR__ . "/alipay_sdk/request/AlipayTradeQueryRequest.php";

        $object = new \stdClass();
        $object->out_trade_no = $params['out_trade_no'];
        $json = json_encode($object);

        $request = new \AlipayTradeQueryRequest();
        $request->setBizContent($json);
        $result = $this->getAop()->execute($request, null, $appAuthToken);
        print_r($result);
        exit;

        $responseNode = str_replace(".", "_", $request->getApiMethodName()) . "_response";
        $resultCode = $result->$responseNode->code;
        if(!empty($resultCode)&&$resultCode == 10000){
            echo "成功";
        } else {
            echo "失败";
        }
    }
}