<?php

namespace app\plugins\stock\models;

use app\models\BaseActiveRecord;
use app\models\Goods;
use app\plugins\stock\jobs\FillOrderPayedJob;
use app\plugins\stock\jobs\FillOrderPriceLogJob;
use Yii;

/**
 * This is the model class for table "{{%plugin_stock_fill_order}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $user_id
 * @property float $pay_price
 * @property int $created_at
 * @property int $deleted_at
 * @property int $updated_at
 * @property int $is_delete
 * @property string $order_no
 * @property int $is_pay
 */
class FillOrder extends BaseActiveRecord
{
    const IS_PAY_YES = 1;
    const IS_PAY_NO = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%plugin_stock_fill_order}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'user_id'], 'required'],
            [['mall_id', 'user_id', 'created_at', 'deleted_at', 'updated_at', 'is_delete', 'is_pay'], 'integer'],
            [['pay_price'], 'number'],
            [['order_no'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'user_id' => 'User ID',
            'pay_price' => 'Pay Price',
            'created_at' => 'Created At',
            'deleted_at' => 'Deleted At',
            'updated_at' => 'Updated At',
            'is_delete' => 'Is Delete',
            'order_no' => 'Order No',
            'is_pay' => 'Is Pay',
        ];
    }
    public static function getOrderNo($prefix)
    {
        return generate_order_no($prefix);
    }

    public function afterSave($insert, $changedAttributes)
    {
        Yii::warning("FillOrder afterSave status=".$this->is_pay);
        //已迁移到微信回调action方法中
//        if ($this->is_pay == FillOrder::IS_PAY_YES) {
//            \Yii::$app->queue->delay(0)->push(new FillOrderPriceLogJob([
//                'order' => $this,
//                'mall_id' => $this->mall_id
//            ]));
//        }
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
