<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * 分销佣金接口处理类
 * Author: zal
 * Date: 2020-05-26
 * Time: 10:30
 */

namespace app\plugins\stock\forms\api;

use app\core\ApiCode;

use app\models\BaseModel;


use app\plugins\stock\models\AgentOrder;
use app\plugins\stock\models\StockAgentGoods;


class AgentOrderSubmitForm extends BaseModel
{

    public $num;
    public $address;
    public $goods_id;
    public $name;
    public $mobile;

    public function rules()
    {
        return [
            [[ 'goods_id'], 'required'],
            [['num', 'goods_id'], 'integer'],
            [['name','mobile'],'string', 'max' => 45],
            [['address'], 'string', 'max' => 128],
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $agent_goods = StockAgentGoods::findOne(['goods_id' => $this->goods_id, 'user_id' => \Yii::$app->user->identity->id, 'is_delete' => 0]);
        if (!$agent_goods) {
            return $this->returnApiResultData(ApiCode::CODE_FAIL, '商品不存在');
        }
        if ($agent_goods->num < $this->num) {
            return $this->returnApiResultData(ApiCode::CODE_FAIL, '提交失败,库存不足');
        }
        $order = new AgentOrder();
        $order->attributes = $this->attributes;
        $order->user_id = \Yii::$app->user->identity->id;
        $order->mall_id = \Yii::$app->mall->id;
        $order->stock_goods_id = $agent_goods->id;
        $t = \Yii::$app->db->beginTransaction();
        if ($order->save()) {
            $agent_goods->num -= $this->num;
            if ($agent_goods->save()) {
                $t->commit();
                return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '提交成功');
            }
        }
        $t->rollBack();
        return $this->returnApiResultData(ApiCode::CODE_FAIL, '提交失败');
    }
}