<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-06-01
 * Time: 16:29
 */

namespace app\forms\api\coupon;


use app\core\ApiCode;
use app\core\BasePagination;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\models\UserCoupon;

class UserCouponListForm extends BaseModel
{
    public $page;
    public $limit;
    public $status;

    public function rules()
    {
        return [[['page', 'limit', 'status'], 'integer']]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {

        if (!$this->validate()) {
            return $this->returnApiResultData();
        }
        $query = UserCoupon::find()
            ->where(['user_id' => \Yii::$app->user->identity->id, 'is_delete' => 0, 'mall_id' => \Yii::$app->mall->id]);

        if (!$this->status) {
            $query->andWhere(['is_use' => 0, 'is_failure' => 0]);
        }
        if ($this->status == 1) {
            $query->andWhere(['is_use' => 1, 'is_failure' => 0]);
        }
        if ($this->status == 2) {
            $query->andWhere(['is_failure' => 1]);
        }

        /**
         * @var BasePagination $pagination
         */
        $query->page($pagination, $this->limit, $this->page);
        $list = $query->select(['id', 'user_id', 'coupon_id', 'sub_price', 'sub_price', 'sub_price',
            'discount', 'coupon_min_price', 'type', 'is_use', 'discount_limit', 'coupon_data','created_at'])
            ->orderBy(['id' => SORT_DESC])->asArray()->all();
        $newList = [];
        foreach ($list as $item) {
            $item['coupon_data'] = SerializeHelper::decode($item['coupon_data']);
            $item["coupon_data"]["begin_at"] = $item["coupon_data"]["begin_at"] > 0 ? date("Y-m-d H:i:s",$item["coupon_data"]["begin_at"]) : 0;
            $item["coupon_data"]["end_at"] = $item["coupon_data"]["end_at"] > 0 ? date("Y-m-d H:i:s",$item["coupon_data"]["end_at"]) : 0;
            $item["created_at"] = date("Y-m-d H:i:s",$item["created_at"]);
            $newList[] = $item;
        }
        return $this->returnApiResultData(ApiCode::CODE_SUCCESS, '', [
            'list' => $newList,
            'pagination' => [
                'total_count' => $pagination->total_count,
                'page_count' => $pagination->page_count,
                'pageSize' => $pagination->pageSize,
                'current_page' => $pagination->current_page
            ]]);
    }

}
