<?php
namespace app\mch;

use app\mch\handlers\MchModuleHandler;
use yii\base\Module;

class MchModule extends Module {

    public $layout = "main";

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}