<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-07-21
 * Time: 17:20
 */

namespace app\plugins\distribution\forms\mall;


use app\core\ApiCode;
use app\models\BaseModel;
use app\plugins\distribution\models\RebuyPriceLog;

class RebuyPriceListForm extends BaseModel
{

    public $keyword;
    public $page;

    public function rules()
    {
        return [[['page'], 'integer']]; // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $list = RebuyPriceLog::find()->where([
            'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0
        ])->with('user')
            ->page($pagination, 20, $this->page)->orderBy(['created_at' => SORT_DESC])->asArray()->all();

        foreach ($list as &$item){
            $item['created_at']=date('Y-m-d H:i:s',$item['created_at']);
        }

        return [
            'code' => ApiCode::CODE_SUCCESS,
            'msg' => '',
            'data' => [
                'list' => $list,
                'pagination' => $pagination,
            ]
        ];

    }


}