<?php
/**
 * @link:http://www.gdqijianshi.com/
 * @copyright: Copyright (c) 2020 广东七件事集团
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-05-08
 * Time: 15:41
 */

namespace app\plugins\business_card;

use app\handlers\BaseHandler;
use app\helpers\PluginHelper;
use app\plugins\business_card\forms\common\Common;
use app\plugins\business_card\handlers\HandlerRegister;

class Plugin extends \app\plugins\Plugin
{
    public function getIsSetToQuickMenu()
    {
        //这里去缓存里面查询
        return false; // TODO: Change the autogenerated stub
    }

    //为主菜单提供的菜单
    public function getMenuForMainMenu()
    {
        return [
            'key' => $this->getName(),
            'name' => 'AI智能名片',
            'route' => $this->getIndexRoute(),
            'children' => $this->getMenus(),
            'icon' => 'statics/img/mall/nav/finance.png',
            'icon_active' => 'statics/img/mall/nav/finance-active.png',
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * 插件小程序端链接
     * @return array
     */
    public function getPickLink()
    {
        $iconBaseUrl = PluginHelper::getPluginBaseAssetsUrl($this->getName()) . '/img/pick-link';

        return [
            [
                'key' => 'business_card',
                'name' => '名片首页',
                'open_type' => '',
                'icon' => $iconBaseUrl . '/icon-spell_group.png',
                'value' => '/plugins/business-card/index',
            ],
            [
                'key' => 'business_card',
                'name' => '雷达',
                'open_type' => '',
                'icon' => $iconBaseUrl . '/icon-spell_group.png',
                'value' => '/plugins/business-card/log/log',
            ],
            [
                'key' => 'business_card',
                'name' => '消息',
                'open_type' => '',
                'icon' => $iconBaseUrl . '/icon-spell_group.png',
                'value' => '/plugins/business-card/message/list',
            ],
            [
                'key' => 'business_card',
                'name' => '客户',
                'open_type' => '',
                'icon' => $iconBaseUrl . '/icon-spell_group.png',
                'value' => '/plugins/business-card/client/list',
            ],[
                'key' => 'business_card',
                'name' => '我的',
                'open_type' => '',
                'icon' => $iconBaseUrl . '/icon-spell_group.png',
                'value' => '/plugins/business-card/my/index',
            ],
        ];
    }

    public function getMenus()
    {
        return [
            [
                'name' => '基础配置',
                'route' => 'plugin/business_card/mall/setting/index',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '海报',
                'route' => 'plugin/business_card/mall/setting/poster',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '标签库',
                'route' => 'plugin/business_card/mall/setting/tag',
                'icon' => 'el-icon-setting',
            ],
            [
                'name' => '部门',
                'route' => 'plugin/business_card/mall/business-card-department/index',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '新增部门',
                        'route' => 'plugin/business_card/mall/business-card-department/add',
                    ],
                    [
                        'name' => '编辑部门',
                        'route' => 'plugin/business_card/mall/business-card-department/edit',
                    ],
                    [
                        'name' => '部门下用户列表',
                        'route' => 'plugin/business_card/mall/business-card-auth/look-user',
                    ],
                ]
            ],
            [
                'name' => '职位',
                'route' => 'plugin/business_card/mall/business-card-position/index',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '新增职位',
                        'route' => 'plugin/business_card/mall/business-card-position/add',
                    ],
                    [
                        'name' => '编辑职位',
                        'route' => 'plugin/business_card/mall/business-card-position/edit',
                    ],
                ]
            ],
            [
                'name' => '名片',
                'route' => 'plugin/business_card/mall/business-card/index',
                'icon' => 'el-icon-setting',
                'action' => [
                    [
                        'name' => '查看名片',
                        'route' => 'plugin/business_card/mall/business-card/detail',
                    ],
                ]
            ],
        ];
    }

    public function getIndexRoute()
    {
        return 'plugin/business_card/mall/setting/index';
    }

    public function getStatisticsMenus()
    {
        return [
            'name' => $this->getDisplayName(),
            'key' => $this->getName(),
            'route' => 'mall/distribution-statistics/index',
        ];
    }

    /**
     * 插件唯一id，小写英文开头，仅限小写英文、数字、下划线
     * @return string
     */
    public function getName()
    {
        return 'business_card';
    }

    /**
     * 插件显示名称
     * @return string
     */
    public function getDisplayName()
    {
        return 'AI智能名片';
    }


    public function getIsPlatformPlugin()
    {
        return true;
    }

    public function handler()
    {
        $register = new HandlerRegister();
        $HandlerClasses = $register->getHandlers();
        foreach ($HandlerClasses as $HandlerClass) {
            $handler = new $HandlerClass();
            if ($handler instanceof BaseHandler) {
                /** @var BaseHandler $handler */
                $handler->register();
            }
        }
        return $this;
    }

    /**
     * 获取名片信息
     * @param \app\models\User $user
     * @return array
     * @throws \Exception
     */
    public function getUserInfo($user)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        /** @var Distribution $distributions */
        //$distributions = $common->getDistributionInfo($user);
        return [
            'business_card' => [
//                'total_price' => $distributions["total_price"]??'0.00',
//                'frozen_price' => $distributions["frozen_price"]??'0.00',
//                'yesterday_price' => $distributions["yesterday_price"] ?? '0.00',
//                'level_name' => $distributions["level_name"],
                'sign' => $this->getName(),
                'plugin_name'=>$this->getDisplayName(),
                'logo'=>$this->getLogo()
            ]
        ];
    }

    /**
     * 获取分销记录列表
     * @param $user
     * @param $params
     * @return array
     * @throws \Exception
     */
    public function getList($user, $params)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getDistributionLogList($user, $params);
        return $returnData;
    }

    /**
     * 获取分销订单
     * @param $order
     * @return array
     * @throws \Exception
     */
    public function getDistributionOrderList($order)
    {
        $common = Common::getCommon(\Yii::$app->mall);
        $returnData = $common->getDistributionOrderList($order);
        return $returnData;
    }

    public function getLogo()
    {
        // TODO: Implement pluginLogo() method.

        return '';
    }

    public function getPriceTypeName($price_log_id=0)
    {
        // TODO: Implement getPriceTypeName() method.
    }
}
