<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%test_model}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $created_at
 * @property int $deleted_at
 * @property int $updated_at
 * @property int $is_delete
 * @property int $status
 */
class TestModel extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%test_model}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id'], 'required'],
            [['mall_id', 'created_at', 'deleted_at', 'updated_at', 'is_delete', 'status'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'created_at' => 'Created At',
            'deleted_at' => 'Deleted At',
            'updated_at' => 'Updated At',
            'is_delete' => 'Is Delete',
            'status' => 'Status',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            Yii::warning('当前插入之后返回的ID：' . $this->id);
        }
        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
